SonarCloud
WebUI-Project-Based-07-vk/BackEnd pull request #33
Opened 2024-07-15 08:25 UTC by HalynaProlubshchykova

Connection to SonarCloud

2024-07-15 08:58 UTC, olehpona reviewed
looks good!

2024-07-15 09:13 UTC, tufned approved these changes

2024-07-15 13:21 UTC, MrAK-dev approved these changes
Code looks good!

2024-07-15 13:43 UTC, SachkovaYuliia approved these changes

2024-07-15 20:45 UTC, olehpona approved these changes
looks good!

2024-07-16 13:26 UTC, vlad-khrychov requested changes

2024-07-16 13:26 UTC, vlad-khrychov commented on sonar-project.properties
> +sonar.coverage.exclusions=**/src/constants/*, **/src/tests/**/*, **/*.styles.ts
Do we have styles on back end part?
```suggestion
sonar.coverage.exclusions=**/src/constants/*, **/src/tests/**/*
```

2024-07-16 13:26 UTC, vlad-khrychov commented on sonar-project.properties
> +sonar.tests=./src/tests
In this repo tests are placed in folder `test`.
```suggestion
sonar.tests=./src/test
```

2024-07-17 07:46 UTC, vlad-khrychov requested changes

2024-07-17 07:46 UTC, vlad-khrychov commented on sonar-project.properties
> +sonar.exclusions=**/src/test/**/*
```suggestion
sonar.exclusions=**/src/test/**/*, **/src/consts/*, docs/**
```

2024-07-17 13:17 UTC, vlad-khrychov approved these changes

2024-07-17 13:53 UTC, merged