Feature/18/generate-jwt-tokens
WebUI-Project-Based-07-vk/BackEnd pull request #34
Opened 2024-07-15 15:15 UTC by SeredenkoDS

Created a script to update JWT secrets inside .env.local file. Use "npm run jwt" command in the "backend" folder to update secrets.

2024-07-15 20:44 UTC, olehpona approved these changes
Everything works perfect!

2024-07-16 14:59 UTC, MrAK-dev approved these changes
Looks good!

2024-07-16 18:57 UTC, HalynaProlubshchykova approved these changes
Everything works

2024-07-17 07:30 UTC, vlad-khrychov commented on package.json
> +	"jwt": "node src/utils/updateEnvWithNewJWTKeys.js .env.local"
Please, replace the symbol `tab` by 4 spaces. And check your VS code settings.

2024-07-20 16:23 UTC, tufned requested changes
Everything works as expected 👍 
But please format `updateEnvWithNewJWTKeys.js` file with eslint 

<img width="715" alt="Знімок екрана 2024-07-20 о 19 22 17" src="https://github.com/user-attachments/assets/226b8e0b-5f6a-4651-9153-d3245835cddd">

2024-07-24 18:09 UTC, SeredenkoDS commented
Thank you for the comment, made the requested changes!

2024-07-24 18:12 UTC, tufned approved these changes
Nice!

2024-07-26 13:02 UTC, vlad-khrychov approved these changes

2024-07-29 14:34 UTC, merged