Task #23 (test for idValidation middleware)
WebUI-Project-Based-07-vk/BackEnd pull request #35
Opened 2024-07-16 11:13 UTC by SeredenkoDS

Run the test using 'npx jest src/test/unit/middlewares/idValidation.spec.js'

2024-07-16 16:01 UTC, MrAK-dev approved these changes

2024-07-17 12:24 UTC, olehpona approved these changes

2024-07-18 13:43 UTC, vlad-khrychov requested changes

2024-07-18 13:43 UTC, vlad-khrychov commented on src/test/unit/middlewares/idValidation.spec.js
> +const { createError } = require('~/utils/errorsHelper')
I think better way will to mock `createError` with some implementation. And check what obtains this function and that it was called.

2024-07-18 13:43 UTC, vlad-khrychov commented on src/test/unit/middlewares/idValidation.spec.js
> +const { INVALID_ID } = require('~/consts/errors')
If you mock `createError` you could delete this import.

2024-07-19 07:43 UTC, vlad-khrychov requested changes

2024-07-19 07:43 UTC, vlad-khrychov commented on src/test/unit/middlewares/idValidation.spec.js
> +    return new Error();
```suggestion
    return new Error("test error");
```

2024-07-19 07:43 UTC, vlad-khrychov commented on src/test/unit/middlewares/idValidation.spec.js
> +    expect(next).not.toHaveBeenCalled()
```suggestion
    } catch (error) {
     expect(error.message).toEqual("test error")
    }
    expect(createError).toHaveBeenCalledWith(400, INVALID_ID);
    expect(next).not.toHaveBeenCalled()
```

2024-07-20 16:40 UTC, tufned approved these changes
There are a few semicolons
You can use  _prettier_ to format file
Overall looks good)

2024-07-21 18:53 UTC, HalynaProlubshchykova approved these changes

2024-07-24 22:47 UTC, SeredenkoDS commented
Thank you for the comments! Made the suggested changes.

2024-07-26 12:52 UTC, vlad-khrychov approved these changes

2024-07-29 14:32 UTC, merged