add integration test for user service
WebUI-Project-Based-07-vk/BackEnd pull request #51
Opened 2024-07-22 13:56 UTC by SachkovaYuliia

![userService](https://github.com/user-attachments/assets/b085980e-e0fb-4ba3-bbb6-65e8b1aa85ae)

2024-07-23 10:18 UTC, olehpona commented on src/test/integration/services/userService.spec.js
> +      expect(retrievedUser._id.toString()).toEqual(user._id.toString())
Is it necessary to check the string variant of the ObjectId here?
Maybe you can just use
```js
expect(retrievedUser._id).toEqual(user._id)
```

2024-07-23 10:18 UTC, olehpona approved these changes

2024-07-23 11:55 UTC, grbvtsk approved these changes

2024-07-24 16:52 UTC, HalynaProlubshchykova approved these changes

2024-07-25 13:40 UTC, MrAK-dev approved these changes

2024-07-25 14:00 UTC, vlad-khrychov requested changes
After fixing all comments do not forget write to the discord chat about it.

2024-07-25 14:00 UTC, vlad-khrychov commented on src/test/integration/services/userService.spec.js
> +  await mongoose.connect(uri, { useNewUrlParser: true, useUnifiedTopology: true })
I already saw the similar code. Create issue to move this logic to the some external file, as test setup.

2024-07-25 14:00 UTC, vlad-khrychov commented on src/test/integration/services/userService.spec.js
> +      }
We discussed that it is not correct way to test errors.

2024-07-31 07:23 UTC, vlad-khrychov approved these changes

2024-07-31 07:23 UTC, vlad-khrychov commented on src/test/integration/setupTests.js
Good approach, discuss with the team, maybe someone wants to modify previous tests with this setup. Or they should be aware of this possibility for the next tests.

2024-07-31 13:46 UTC, merged