added password hash functionality
WebUI-Project-Based-07-vk/BackEnd pull request #53
Opened 2024-07-22 18:56 UTC by olehpona

Added hashHelper util with 2 async function
```ts 
getHash(plainText: string) -> string
compareHashes(plainText: string, hash: string) -> boolean
```
Also you need to set env variable HASH_SALT_ROUNDS to make that util works properly

2024-07-23 21:01 UTC, SachkovaYuliia approved these changes

2024-07-24 17:34 UTC, HalynaProlubshchykova approved these changes

2024-07-24 18:35 UTC, tufned approved these changes
Looks good!

Just avoid changing the line separators

2024-07-25 08:24 UTC, grbvtsk approved these changes

2024-07-25 13:54 UTC, vlad-khrychov requested changes

2024-07-25 13:54 UTC, vlad-khrychov commented on src/utils/hashHelper.js
> +    throw PASSWORD_HASH_ERROR
Here did you plan to throw the function? Or object that this function returns?

2024-07-25 14:16 UTC, vlad-khrychov approved these changes

2024-07-25 16:39 UTC, merged