Feature/43/location-service-cities
WebUI-Project-Based-07-vk/BackEnd pull request #61
Opened 2024-07-25 09:54 UTC by SeredenkoDS

As an extension of #42, which pulls a list of countries using CountryStateCity API, this one, #43, pulls a list of cities.
Example usage: http://localhost:8080/get-city-list/UA (UA can be changed into an ISO2 code of any other country you see at http://localhost:8080/get-country-list )

When reviewing, check if the URL like http://localhost:8080/get-city-list/UA works for you, and if it does, feel free to approve. Thanks!

2024-07-25 13:50 UTC, MrAK-dev approved these changes

2024-07-26 06:56 UTC, grbvtsk approved these changes

2024-07-26 10:34 UTC, vlad-khrychov requested changes

2024-07-26 10:34 UTC, vlad-khrychov commented on src/services/locationServiceCities.js
> +    var headers = new Headers()
```suggestion
    const headers = new Headers()
```

2024-07-26 10:34 UTC, vlad-khrychov commented on src/services/locationServiceCities.js
> +    var requestOptions = {
```suggestion
    const requestOptions = {
```

2024-07-26 10:34 UTC, vlad-khrychov commented on src/services/locationServiceCountries.js
> +    var headers = new Headers()
```suggestion
    const headers = new Headers()
```

2024-07-26 10:34 UTC, vlad-khrychov commented on src/services/locationServiceCountries.js
> +    var requestOptions = {
```suggestion
    const requestOptions = {
```

2024-07-26 10:34 UTC, vlad-khrychov commented on src/services/locationServiceCountries.js
> +    }
Throw here the custom error just like in Countries

2024-07-26 13:39 UTC, olehpona approved these changes

2024-07-26 14:41 UTC, vlad-khrychov requested changes
You forget to delete `var`-s.

2024-07-26 14:41 UTC, vlad-khrychov commented on src/services/locationServiceCities.js
> +      return JSON.parse(result)
Can we use here 
```suggestion
      const result = await response.json()
      return result 
```

2024-07-30 06:55 UTC, vlad-khrychov approved these changes

2024-07-30 07:12 UTC, merged