Feature/80/implement add subject endpoint
WebUI-Project-Based-07-vk/BackEnd pull request #90
Opened 2024-08-09 08:36 UTC by MrAK-dev

Task completed without swagger documentation, will add separate task for creating swagger doc.

![image](https://github.com/user-attachments/assets/e4b9dde8-a790-4467-a2fb-0f04cfbba79f)

to run tests:
npm run test subject

2024-08-09 09:16 UTC, HalynaProlubshchykova approved these changes

2024-08-09 09:34 UTC, grbvtsk approved these changes

2024-08-12 08:04 UTC, vlad-khrychov requested changes

2024-08-12 08:04 UTC, vlad-khrychov commented on src/services/subject.js
> +      throw createError(500, INTERNAL_SERVER_ERROR)
Try to add not 500th error

2024-08-12 08:04 UTC, vlad-khrychov commented on src/services/subject.js
> +      throw createError(500, INTERNAL_SERVER_ERROR)
Try to add not 500th error

2024-08-12 12:09 UTC, SachkovaYuliia approved these changes

2024-08-12 14:52 UTC, vlad-khrychov approved these changes

2024-08-12 15:07 UTC, merged